# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndexUpdater
                                 A QGIS plugin
 This Plugin update index in activ layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-06
        copyright            : (C) 2021 by MorriganR
        email                : MorriganR@qgis.com.ua
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndexUpdater class from file IndexUpdater.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .index_updater import IndexUpdater
    return IndexUpdater(iface)
